language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - ruby-head
  - rbx-2
  - rbx-head
addons:
  postgresql: "9.3"
env:
  - "RAILS_VERSION=4.1.0"
matrix:
  allow_failures:
    - env: "RAILS_VERSION=master"
    - rvm: ruby-head
    - rvm: rbx-head
script:
  - cd spec/dummy/rails-$RAILS_VERSION; bundle exec rake db:migrate
  - cd ../../../; bundle exec rake spec
before_script:
  - psql -c 'create database activerecord_postgresql_postgis_test;' -U postgres
